### PR TITLE
Handle child resource direct delete for VerrazzanoHelidonWorkload

### PR DESCRIPTION
**Pull request by arjav-desai**
# Description

Currently, when VerrazzanoHelidonWorkload is created/deleted/updated, we update Deployment/Service based on that accordingly. However, if the Deployment/Service is directly deleted/updated then it should revert back to expected config/setup based on VerrazzanoHelidonWorkload which is not happening. This PR fixes that.

Fixes VZ-2306

# Checklist 

As the author of this PR, I have:

- [x] Checked that I included or updated copyright and license notices in all files that I altered
- [x] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

### CODE REVIEW

**Comment by arjav-desai** [comment]
Test, direct delete Service and its recreated 
`
$kubectl get all -n hello-helidon
NAME                                            READY   STATUS    RESTARTS   AGE
pod/hello-helidon-deployment-6d9cdb8959-74m24   2/2     Running   0          77s

NAME                               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/hello-helidon-deployment   ClusterIP   10.96.32.249   <none>        8080/TCP   77s

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-helidon-deployment   1/1     1            1           77s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-helidon-deployment-6d9cdb8959   1         1         1       77s

$kubectl delete service/hello-helidon-deployment -n hello-helidon
service "hello-helidon-deployment" deleted

$kubectl get all -n hello-helidon
NAME                                            READY   STATUS    RESTARTS   AGE
pod/hello-helidon-deployment-6d9cdb8959-74m24   2/2     Running   0          106s

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/hello-helidon-deployment   ClusterIP   10.96.113.248   <none>        8080/TCP   4s

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-helidon-deployment   1/1     1            1           106s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-helidon-deployment-6d9cdb8959   1         1         1       106s`

**Comment by arjav-desai** [comment]
Test, direct delete Deployment and its recreated
`kubectl get all -n hello-helidon
NAME                                            READY   STATUS    RESTARTS   AGE
pod/hello-helidon-deployment-6d9cdb8959-74m24   2/2     Running   0          116s

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/hello-helidon-deployment   ClusterIP   10.96.113.248   <none>        8080/TCP   14s

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-helidon-deployment   1/1     1            1           116s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-helidon-deployment-6d9cdb8959   1         1         1       116s

$kubectl delete deploy/hello-helidon-deployment -n hello-helidon
deployment.apps "hello-helidon-deployment" deleted

$kubectl get all -n hello-helidon
NAME                                            READY   STATUS        RESTARTS   AGE
pod/hello-helidon-deployment-6d9cdb8959-74m24   0/2     Terminating   0          2m22s
pod/hello-helidon-deployment-6d9cdb8959-88q7k   2/2     Running       0          4s

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/hello-helidon-deployment   ClusterIP   10.96.113.248   <none>        8080/TCP   40s

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-helidon-deployment   1/1     1            1           5s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-helidon-deployment-6d9cdb8959   1         1         1       5s`

**Review by fredtibbitts — APPROVED** [review]
LGTM. I'll make a note to add this to the WebLogic and Coherence controllers as well, assuming @kminder agrees that this is the desired behavior.

**Review by kminder — APPROVED** [review]
Approved.

**Pull request merged**
