### PR TITLE
Jshum/vz 3787

### PR DESCRIPTION
**Pull request by jshum2479**
# Description

This PR changes verrazzano bobs-book and todo-list examples to use WKO auxiliary image in the operator environment. It has dependency PR https://github.com/verrazzano/examples/pull/86

Fixes VZ-3787

# Checklist 

As the author of this PR, I have:

- [x ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

### CODE REVIEW

**Review by markxnelson — APPROVED** [review]

**Comment by bobdonat** [comment]
@markxnelson should this change also be made to the multicluster version of the todo-list yaml

**Comment by markxnelson** [comment]
@bobdonat yeah you're right - thanks -- @jshum2479 please do that one too

**Comment by jshum2479** [comment]
ok, I am making the change to multicluster todo now

**Comment by jshum2479** [comment]
Test looks good:

https://build.verrazzano.io/job/verrazzano/job/jshum%252Fvz-3787/5/

**Comment by bobdonat** [comment]
To test bobs-books and the multi-cluster you need to "Build with Parameters" and select "RUN_SLOW_TESTS" amd "TRIGGER_FULL_TESTS".

**Review by markxnelson — DISMISSED** [review]

**Review by markxnelson — DISMISSED** [review]

**Review by markxnelson — APPROVED** [review]

**Pull request merged**
