### PR TITLE
Disable KinD support in installer

### PR DESCRIPTION
**Pull request by desagar**
Installer will fail fast if CLUSTER_TYPE is not OKE or OLCNE. KIND is no longer an allowed option.
Removed install-kind.sh and scripts to create/delete KinD cluster.

### CODE REVIEW

**Comment by mgianatagh** [comment]
Should we also remove `install/config/images`?

**Comment by bobdonat** [comment]
remove load-images.sh too?

**Comment by desagar** [comment]
Good point, @mgianatagh and @bobdonat - removed install/config/images and load-images.sh as well

**Comment by bobdonat** [comment]
There are still refs to KIND in install-hello-world.sh and install-sock-shop.sh

**Comment by desagar** [comment]
Also removed all special handling for KinD in the install scripts.

**Comment by desagar** [comment]
> There are still refs to KIND in install-hello-world.sh and install-sock-shop.sh

Thanks Bob.

**Comment by desagar** [comment]
Removed KIND references from application install scripts install-hello-world.sh and install-sock-shop.sh

**Review by markxnelson — APPROVED** [review]

**Pull request merged**
