### PR TITLE
VZ-10511: Uptake capi controller version 1.5.0

### PR DESCRIPTION
**Pull request by Abhijithang**
This PR uptakes CAPI controller version 1.5.0

### CODE REVIEW

**Review by mgianatagh — APPROVED** [review]

**Comment by prasad-shirodkar** [comment]
Please delete the previous [v1.4.2](https://github.com/verrazzano/verrazzano/tree/abnadago/VZ-10511-uptake-capi-1.5/platform-operator/capi/cluster-api/v1.4.2) directory of capi.

**Comment by prasad-shirodkar** [comment]
CHANGES.md should be updated.

**Comment by Abhijithang** [comment]
> Please delete the previous [v1.4.2](https://github.com/verrazzano/verrazzano/tree/abnadago/VZ-10511-uptake-capi-1.5/platform-operator/capi/cluster-api/v1.4.2) directory of capi.

If it is not required I could delete it but just wondering why do we need a directory then?

**Comment by Abhijithang** [comment]
> CHANGES.md should be updated.

Sure, will do. Thanks.

**Comment by prasad-shirodkar** [comment]
> > Please delete the previous [v1.4.2](https://github.com/verrazzano/verrazzano/tree/abnadago/VZ-10511-uptake-capi-1.5/platform-operator/capi/cluster-api/v1.4.2) directory of capi.
> 
> If it is not required I could delete it but just wondering why do we need a directory then?

@theabmitra might have an answer for your question.

**Pull request closed without merging**
