### PR TITLE
update verrazzano component images to 0.4.0 prior to 0.4 release

### PR DESCRIPTION
**Pull request by guoyongzhang**

### CODE REVIEW

**Review by markxnelson — APPROVED** [review]

**Comment by markxnelson** [comment]
LGTM, please ask @gilbode or @mgianatagh to double check it

**Comment by desagar** [comment]
lgtm as well. Not approving since we are awaiting feedback from Mike and Mike

**Comment by mgianatagh** [comment]
Do the examples images in the model file for bob's books and Helidon hello world also need to be updated to use the new tagging format?

**Comment by guoyongzhang** [comment]
> Do the examples images in the model file for bob's books and Helidon hello world also need to be updated to use the new tagging format?

They had been updated before.

**Review by mgianatagh — APPROVED** [review]

**Pull request merged**
